dist: focal
language: python
python:
  - "3.11"

cache: pip

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations
  - python manage.py migrate


after_script:
  - coveralls

script:
  - black .
  - black --check .
  - flake8 .
  - coverage run --source=chatroom,vibematch,login,static,templates,dashboard,vibecheck,user_profile,search manage.py test --no-input


deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-west-2"
  app: "vcheck-app-1114b"
  env: "vc-env-1114bb"
  bucket_name: "elasticbeanstalk-us-west-2-284687301079"
  bucket_path: "vcheck-app-1114b/"
  on:
    repo: gcivil-nyu-org/Wednesday-Fall2023-Team-1
    branch: develop